import os from 'node:os';
import path from 'node:path';
import { DEFAULT_TURN_START_DIRECTIVE, DEFAULT_TURN_CONTINUE_DIRECTIVE } from './prompt-directives.mjs';

const home = os.homedir();
const dataDir = process.env.SELFRUN_SERVER_DATA_DIR || path.join(home, '.selfrun-server');

export const config = Object.freeze({
  version: '4.0.0-dev2',
  host: process.env.SELFRUN_SERVER_HOST || '127.0.0.1',
  port: Number(process.env.SELFRUN_SERVER_PORT || 17831),
  dataDir,
  stateFile: path.join(dataDir, 'state.json'),
  eventsFile: path.join(dataDir, 'events.jsonl'),
  tokenFile: path.join(dataDir, 'token'),
  driveAuthClientFile: process.env.SELFRUN_DRIVE_AUTH_CLIENT_FILE || path.join(dataDir, 'drive-auth-client.json'),
  driveAuthTokenFile: process.env.SELFRUN_DRIVE_AUTH_TOKEN_FILE || path.join(dataDir, 'drive-auth-token.json'),
  browserLogFile: path.join(dataDir, 'chromium.log'),
  browserProfile: process.env.SELFRUN_BROWSER_PROFILE || path.join(home, '.config', 'chromium'),
  browserPort: Number(process.env.SELFRUN_BROWSER_PORT || 19227),
  browserActivityDir: process.env.SELFRUN_BROWSER_ACTIVITY_DIR || path.join(home, '.browser-target-activity'),
  browserTargetIdleMs: Number(process.env.SELFRUN_BROWSER_TARGET_IDLE_MS || 3600000),
  browserTargetSweepMs: Number(process.env.SELFRUN_BROWSER_TARGET_SWEEP_MS || 60000),
  chromiumCommand: process.env.SELFRUN_CHROMIUM || 'chromium-browser',
  browserClientProfile: process.env.SELFRUN_BROWSER_CLIENT_PROFILE || 'native',
  browserAndroidUserAgent: process.env.SELFRUN_BROWSER_ANDROID_USER_AGENT || '',
  browserAndroidModel: process.env.SELFRUN_BROWSER_ANDROID_MODEL || 'Android',
  browserAndroidVersion: process.env.SELFRUN_BROWSER_ANDROID_VERSION || '17',
  browserAndroidPlatformVersion: process.env.SELFRUN_BROWSER_ANDROID_PLATFORM_VERSION || '17.0.0',
  browserAndroidBuildId: process.env.SELFRUN_BROWSER_ANDROID_BUILD_ID || 'UNKNOWN',
  browserAndroidChromeVersion: process.env.SELFRUN_BROWSER_ANDROID_CHROME_VERSION || '149.0.7827.155',
  browserAndroidAcceptLanguage: process.env.SELFRUN_BROWSER_ANDROID_ACCEPT_LANGUAGE || 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
  browserAndroidWidth: Number(process.env.SELFRUN_BROWSER_ANDROID_WIDTH || 412),
  browserAndroidHeight: Number(process.env.SELFRUN_BROWSER_ANDROID_HEIGHT || 915),
  browserAndroidDeviceScaleFactor: Number(process.env.SELFRUN_BROWSER_ANDROID_DPR || 3),
  browserIdleRecycleMs: Number(process.env.SELFRUN_BROWSER_IDLE_RECYCLE_MS || 60000),
  browserIdleRssMb: Number(process.env.SELFRUN_BROWSER_IDLE_RSS_MB || 600),
  browserOrphanGcEnabled: process.env.SELFRUN_BROWSER_ORPHAN_GC !== '0',
  probeIntervalMs: Number(process.env.SELFRUN_PROBE_INTERVAL_MS || 60000),
  stallAfterMs: Number(process.env.SELFRUN_STALL_AFTER_MS || 600000),
  drivePollMs: Number(process.env.SELFRUN_DRIVE_POLL_MS || 1000),
  preparedPollMs: Number(process.env.SELFRUN_PREPARED_POLL_MS || 1000),
  driveRunsPath: process.env.SELFRUN_DRIVE_RUNS_PATH || 'selfrun-drive:GPT/Self Run/Runs',
  driveRunsFolderId: process.env.SELFRUN_DRIVE_RUNS_FOLDER_ID || '1LaIjBACRA4bgTblTOHOki5OF39Cyxi4c',
  promptDirectivesFile: process.env.SELFRUN_PROMPT_DIRECTIVES_FILE
    || path.join(dataDir, 'prompt-directives.json'),
  turnStartDirective: process.env.SELFRUN_TURN_START_DIRECTIVE || DEFAULT_TURN_START_DIRECTIVE,
  recoveryPrompt: process.env.SELFRUN_RECOVERY_PROMPT || DEFAULT_TURN_CONTINUE_DIRECTIVE,
  allowUnknownControlRecovery: process.env.SELFRUN_ALLOW_UNKNOWN_CONTROL_RECOVERY === '1',
  dispatchFreshMs: Number(process.env.SELFRUN_DISPATCH_FRESH_MS || 600000),
  dispatchRecoveryMs: Number(process.env.SELFRUN_DISPATCH_RECOVERY_MS || 7200000),
  resumeRetryMs: Number(process.env.SELFRUN_RESUME_RETRY_MS || 30000),
  conversationStateGraceMs: Number(process.env.SELFRUN_CONVERSATION_STATE_GRACE_MS || 5000),
  navigationTimeoutMs: Number(process.env.SELFRUN_NAVIGATION_TIMEOUT_MS || 30000),
  defaultProjectUrl: process.env.SELFRUN_PROJECT_URL || '',
});
