package com.shaterguy.chatgptselfrun;

/** Chat model/reasoning selector for the current composer picker. */
final class ChatReasoningOptionDom {
    private ChatReasoningOptionDom() {}

    static String inline(String selection, String runId) {
        String wanted = ChatReasoningPreferenceStore.normalize(selection);
        boolean captureOnly = ChatReasoningPreferenceStore.KEEP.equals(wanted);
        int ordinal = ChatReasoningPreferenceStore.ordinal(wanted);
        if (ordinal < 0 && !captureOnly) return "";
        return """
                const __sroWanted=__WANTED__,__sroWantedOrdinal=__ORDINAL__,__sroRunId=__RUN_ID__,__sroCaptureOnly=__CAPTURE_ONLY__;
                if(__sroCaptureOnly&&typeof requestedMode!=='undefined'&&requestedMode==='work')return result('READY','WORK 모드에서는 Chat picker 현재값 캡처를 생략합니다.',{strategy:'composer-detent-picker',action:'skip-chat-picker-work',currentMode:'work'});
                const __sroText=value=>String(value??'').replace(/[\\s\\u00a0]+/g,' ').trim().toLowerCase();
                const __sroVisible=e=>!!e&&e.isConnected&&e.offsetParent!==null&&!e.closest?.('[inert],[aria-hidden="true"],[data-active="false"]');
                const __sroLabel=e=>__sroText(e?.getAttribute?.('aria-label')||e?.innerText||e?.textContent||'');
                const __sroLevel=source=>{const v=__sroText(source);if(v.includes('pro extended')||v.includes('프로 확장'))return'pro_extended';if(v.includes('pro standard')||v.includes('프로 표준'))return'pro_standard';if(v.includes('extra high')||v.includes('very high')||v.includes('xhigh')||v.includes('매우 높음'))return'xhigh';if(v.includes('instant')||v.includes('flash')||v.includes('즉시')||v.includes('빠른'))return'instant';if(v.includes('medium')||v.includes('중간')||v.includes('표준'))return'medium';if(v.includes('high')||v.includes('높음'))return'high';if(v==='pro'||v.includes(' sol pro')||v.includes('프로'))return'pro';return'';};
                const __sroModel=source=>{const v=__sroText(source);if(v.includes('sol pro')||v.includes('gpt-5.6 pro')||v==='pro'||v.includes(' 프로'))return'pro';if(v.includes('sol'))return'sol';return'';};
                const __sroStandard=['instant','medium','high','xhigh'],__sroPro=['pro_standard','pro_extended'];
                const __sroWantedPro=__sroWanted==='pro'||__sroPro.includes(__sroWanted),__sroOrder=__sroWantedPro?__sroPro:__sroStandard;
                const __sroInput=(typeof composer!=='undefined'&&composer)||document.querySelector('#prompt-textarea')||[...document.querySelectorAll('textarea,[contenteditable="true"]')].filter(__sroVisible).sort((a,b)=>b.getBoundingClientRect().bottom-a.getBoundingClientRect().bottom)[0]||null;
                const __sroForm=__sroInput?.closest?.('form')||null;
                const __sroPopupSelector='[role="menu"],[role="listbox"],[role="dialog"],[data-testid="composer-intelligence-picker-content"],[data-radix-popper-content-wrapper],[data-slot*="popover-content"],[data-slot*="menu-content"],[data-slot*="sheet-content"]';
                const __sroForbidden=e=>/(send|submit|보내기|stop|중지|voice|음성|microphone|마이크|attach|첨부|upload|업로드|new chat|new conversation|새 채팅|새 대화)/.test(__sroLabel(e)+' '+__sroText(e?.dataset?.testid||''));
                const __sroNear=e=>{if(!e||!__sroInput)return false;if(__sroForm?.contains?.(e))return true;const a=e.getBoundingClientRect(),b=__sroInput.getBoundingClientRect();return a.bottom>=b.top-320&&a.top<=b.bottom+320&&a.right>=b.left-420&&a.left<=b.right+420;};
                const __sroRoots=[...document.querySelectorAll('button,[role="button"],[aria-haspopup],[aria-expanded],[data-testid*="model"],[data-testid*="reason"],[data-testid*="effort"]')].filter(__sroVisible).filter(e=>!e.closest(__sroPopupSelector)).filter(e=>!__sroForbidden(e)).map((element,index)=>{const label=__sroLabel(element),testid=__sroText(element.dataset?.testid||'');let score=0;if(/reason|thinking|effort|추론/.test(label+' '+testid))score+=150;if(__sroLevel(label))score+=100;if(/model|모델|gpt/.test(label+' '+testid))score+=35;if(element.hasAttribute('aria-haspopup'))score+=45;if(element.hasAttribute('aria-expanded'))score+=35;if(__sroNear(element))score+=190;return{element,index,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.index-b.index);
                const __sroAnimated=[...document.querySelectorAll('[data-animated-slider-trigger="true"]')].find(__sroVisible)||null;
                const __sroAnimatedRoot=__sroAnimated?.closest?.('button,[role="button"],[aria-haspopup],[aria-expanded]')||null;
                const __sroRoot=__sroAnimatedRoot&&__sroVisible(__sroAnimatedRoot)&&__sroNear(__sroAnimatedRoot)?__sroAnimatedRoot:(__sroRoots[0]?.element||null);
                const __sroOpen=[...document.querySelectorAll(__sroPopupSelector)].filter(__sroVisible);
                const __sroHeader=[...document.querySelectorAll('button,[role="button"],[aria-haspopup],[aria-expanded]')].filter(__sroVisible).filter(e=>__sroOpen.some(p=>p.contains(e))).find(e=>(e.hasAttribute('aria-haspopup')||e.hasAttribute('aria-expanded'))&&!!__sroLevel(__sroLabel(e)))||null;
                const __sroExplicitModelRow=[...document.querySelectorAll('[role="menuitem"][aria-label]')].filter(__sroVisible).find(e=>__sroLabel(e)==='select model'||__sroLabel(e)==='모델 선택')||null;
                const __sroModelRow=__sroExplicitModelRow||__sroHeader;
                const __sroPerformance=[...document.querySelectorAll('[role="menuitem"][aria-label]')].filter(__sroVisible).find(e=>{const v=__sroLabel(e);return v==='성능'||v==='performance';})||null;
                const __sroSliders=[...document.querySelectorAll('[role="slider"],input[type="range"]')].filter(__sroVisible).filter(e=>e.getAttribute('aria-orientation')!=='vertical');
                const __sroSlider=__sroPerformance?.querySelector?.('[role="slider"],input[type="range"]')||__sroSliders.find(e=>__sroPerformance?.contains?.(e))||__sroSliders.find(e=>{if(!__sroPerformance)return false;const a=e.getBoundingClientRect(),b=__sroPerformance.getBoundingClientRect();return a.top>=b.top-8&&a.bottom<=b.bottom+8;})||__sroSliders.find(e=>__sroOpen.some(p=>p.contains(e)))||null;
                const __sroRadios=[...document.querySelectorAll('[role="menuitemradio"],[role="radio"],[role="option"]')].filter(__sroVisible).map(element=>({element,model:__sroModel(__sroLabel(element)),selected:element.getAttribute('aria-checked')==='true'||element.getAttribute('aria-selected')==='true'||element.dataset?.state==='checked'})).filter(x=>x.model);
                const __sroSelectedModel=__sroRadios.find(x=>x.selected)?.model||'';
                const __sroObserved=__sroLevel(__sroSlider?.getAttribute?.('aria-valuetext')||'')||__sroLevel(__sroModelRow?.innerText||'')||__sroLevel(__sroRoot?.innerText||__sroRoot?.getAttribute?.('aria-label')||'');
                const __sroCurrentModel=__sroSelectedModel||__sroModel(__sroModelRow?.innerText||'')||__sroModel(__sroRoot?.innerText||'')||((__sroPro.includes(__sroObserved)||__sroObserved==='pro')?'pro':(__sroStandard.includes(__sroObserved)?'sol':''));
                const __sroStateKey='selfrun-drive:chat-reasoning-detent:'+__sroRunId;
                const __sroNow=Date.now(),__sroTimeoutMs=30000,__sroRetryMs=2400;
                let __sroState={startedAt:0,requested:'',attempts:0,rootClicks:0,rowClicks:0,modelClicks:0,sliderMoves:0,closeAttempts:0,verified:'',lastAction:'',lastActionAt:0};
                try{const raw=sessionStorage.getItem(__sroStateKey)||localStorage.getItem(__sroStateKey)||'';if(raw)__sroState={...__sroState,...JSON.parse(raw)};}catch(_){}
                if(__sroState.requested&&__sroState.requested!==__sroWanted)__sroState={startedAt:0,requested:__sroWanted,attempts:0,rootClicks:0,rowClicks:0,modelClicks:0,sliderMoves:0,closeAttempts:0,verified:'',lastAction:'',lastActionAt:0};
                if(!(Number(__sroState.startedAt)>0))__sroState.startedAt=__sroNow;__sroState.requested=__sroWanted;__sroState.attempts++;
                const __sroElapsed=__sroNow-__sroState.startedAt,__sroSince=__sroState.lastActionAt?__sroNow-__sroState.lastActionAt:999999;
                const __sroSave=()=>{const value=JSON.stringify(__sroState);try{sessionStorage.setItem(__sroStateKey,value);}catch(_){}try{localStorage.setItem(__sroStateKey,value);}catch(_){}};
                const __sroClear=()=>{try{sessionStorage.removeItem(__sroStateKey);}catch(_){}try{localStorage.removeItem(__sroStateKey);}catch(_){}};
                const __sroMay=(count,max)=>count<1||(__sroSince>=__sroRetryMs&&count<max);
                const __sroFire=(e,type,x,y,buttons)=>{if(!e)return;const init={bubbles:true,cancelable:true,composed:true,clientX:x,clientY:y,button:0,buttons};try{if(type.startsWith('pointer')&&typeof PointerEvent==='function')e.dispatchEvent(new PointerEvent(type,{...init,pointerId:1,pointerType:'mouse',isPrimary:true}));else e.dispatchEvent(new MouseEvent(type,init));}catch(_){}};
                const __sroClick=e=>{if(!e)return;const r=e.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;e.focus?.();__sroFire(e,'pointerdown',x,y,1);__sroFire(e,'mousedown',x,y,1);__sroFire(e,'pointerup',x,y,0);__sroFire(e,'mouseup',x,y,0);__sroFire(e,'click',x,y,0);};
                const __sroClose=()=>{if(__sroRoot?.getAttribute?.('aria-expanded')==='true'){__sroClick(__sroRoot);return'trigger';}document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true,cancelable:true,composed:true}));document.dispatchEvent(new KeyboardEvent('keyup',{key:'Escape',code:'Escape',bubbles:true,cancelable:true,composed:true}));return'escape';};
                const __sroDiagnostics=extra=>({strategy:__sroPerformance?'composer-detent-picker':'slider-model-popover',requested:__sroWanted,requestedOrdinal:__sroWantedOrdinal,captureOnly:__sroCaptureOnly,rootFound:!!__sroRoot,rootLabel:__sroLabel(__sroRoot),popupCandidates:__sroOpen.length,modelRowFound:!!__sroModelRow,performanceFound:!!__sroPerformance,sliderFound:!!__sroSlider,observed:__sroObserved,currentModel:__sroCurrentModel,modelOptions:__sroRadios.map(x=>x.model),rootClicks:__sroState.rootClicks,rowClicks:__sroState.rowClicks,modelClicks:__sroState.modelClicks,sliderMoves:__sroState.sliderMoves,closeAttempts:__sroState.closeAttempts,lastAction:__sroState.lastAction,attempts:__sroState.attempts,elapsedMs:__sroElapsed,timeoutMs:__sroTimeoutMs,...extra});
                const __sroWait=(detail,extra={})=>{__sroSave();return result('UI_WAIT',detail,__sroDiagnostics(extra));};
                const __sroReady=(observed,extra={})=>{const d=__sroDiagnostics({observed,...extra});__sroClear();return result('READY','Chat 추론·모델 적용 확인',d);};
                if(__sroState.verified&&__sroOpen.length===0)return __sroReady(__sroState.verified,{action:'verified-readback'});
                if(__sroCaptureOnly){if(__sroObserved&&__sroOpen.length===0)return __sroReady(__sroObserved,{action:'capture-current'});if(__sroObserved&&__sroOpen.length>0&&__sroMay(__sroState.closeAttempts,2)){__sroState.verified=__sroObserved;__sroState.closeAttempts++;__sroState.lastAction='close-after-capture';__sroState.lastActionAt=__sroNow;__sroSave();const m=__sroClose();return result('UI_WAIT','현재 Chat 추론값 캡처 후 팝업 닫힘 확인 대기',__sroDiagnostics({action:'close-after-capture',closeMethod:m}));}if(__sroOpen.length===0&&__sroRoot&&__sroMay(__sroState.rootClicks,2)){__sroState.rootClicks++;__sroState.lastAction='open-picker-for-capture';__sroState.lastActionAt=__sroNow;__sroSave();__sroClick(__sroRoot);return result('UI_WAIT','현재 Chat 추론값 캡처를 위해 선택기 열림 대기',__sroDiagnostics({action:'open-picker-for-capture'}));}if(__sroElapsed>=__sroTimeoutMs)return result('CHAT_REASONING_READBACK_MISMATCH','현재 Chat 추론 선택값을 확인하지 못했습니다.',__sroDiagnostics({action:'capture-timeout'}));return __sroWait('현재 Chat 추론 선택값 readback 대기',{action:'wait-capture-readback'});}
                const __sroWantedModel=__sroWantedPro?'pro':'sol',__sroModelMismatch=(__sroWantedPro&&(__sroCurrentModel==='sol'||(!__sroCurrentModel&&__sroStandard.includes(__sroObserved))))||(!__sroWantedPro&&(__sroCurrentModel==='pro'||__sroPro.includes(__sroObserved)||__sroObserved==='pro'));
                if(__sroRadios.length>0){const option=__sroRadios.find(x=>x.model===__sroWantedModel);if(option?.selected){__sroState.lastAction='close-model-menu';__sroState.lastActionAt=__sroNow;__sroSave();__sroClose();return result('UI_WAIT','Chat 모델 선택 확인 후 설정 화면 복귀 대기',__sroDiagnostics({action:'close-model-menu'}));}if(option&&__sroMay(__sroState.modelClicks,2)){__sroState.modelClicks++;__sroState.lastAction='select-model';__sroState.lastActionAt=__sroNow;__sroSave();__sroClick(option.element);return result('UI_WAIT','Chat 모델 변경 반영 대기',__sroDiagnostics({action:'select-model',targetModel:__sroWantedModel}));}if(__sroElapsed>=__sroTimeoutMs)return result('CHAT_REASONING_OPTION_UNAVAILABLE','현재 Chat 모델 메뉴에 필요한 모델이 없습니다.',__sroDiagnostics({action:'model-unavailable'}));return __sroWait('Chat 모델 메뉴 옵션 렌더링 대기',{action:'wait-model-options'});}
                if(__sroModelMismatch&&__sroModelRow&&__sroMay(__sroState.rowClicks,2)){__sroState.rowClicks++;__sroState.lastAction='open-model-menu';__sroState.lastActionAt=__sroNow;__sroSave();__sroClick(__sroModelRow);return result('UI_WAIT','Chat 모델 메뉴 열림 대기',__sroDiagnostics({action:'open-model-menu'}));}
                const __sroTargetMatch=__sroWanted==='pro'?(__sroCurrentModel==='pro'):__sroObserved===__sroWanted;
                if(__sroTargetMatch){__sroState.verified=__sroObserved||__sroWanted;__sroSave();if(__sroOpen.length===0)return __sroReady(__sroState.verified,{action:'verified-readback'});if(__sroMay(__sroState.closeAttempts,3)){__sroState.closeAttempts++;__sroState.lastAction='close-target';__sroState.lastActionAt=__sroNow;__sroSave();const m=__sroClose();return result('UI_WAIT','Chat 추론 적용 확인 후 팝업 닫힘 대기',__sroDiagnostics({action:'close-target',closeMethod:m}));}}
                if(__sroSlider&&__sroWanted!=='pro'){
                  const __sroWantedIndex=__sroOrder.indexOf(__sroWanted),__sroCurrentIndex=__sroOrder.indexOf(__sroObserved);
                  if(__sroWantedIndex<0||__sroCurrentIndex<0){if(__sroElapsed>=__sroTimeoutMs)return result('CHAT_REASONING_READBACK_MISMATCH','Chat 추론 슬라이더의 현재 의미값을 판정할 수 없습니다.',__sroDiagnostics({action:'slider-semantic-missing'}));return __sroWait('Chat 추론 슬라이더 의미값 readback 대기',{action:'wait-slider-semantic'});}
                  const __sroInputRange=typeof HTMLInputElement!=='undefined'&&__sroSlider instanceof HTMLInputElement&&__sroSlider.type==='range',__sroCurrentRaw=__sroInputRange?__sroSlider.value:__sroSlider.getAttribute('aria-valuenow');
                  const __sroCurrentNum=__sroCurrentRaw==null||String(__sroCurrentRaw).trim()===''?NaN:Number(__sroCurrentRaw);
                  if(Number.isFinite(__sroCurrentNum)){const direction=Math.sign(__sroWantedIndex-__sroCurrentIndex);if(direction!==0&&__sroState.sliderMoves<10){if(__sroInputRange){const min=Number(__sroSlider.min||0),max=Number(__sroSlider.max||3),step=Number(__sroSlider.step||1)||1,target=Math.max(min,Math.min(max,__sroCurrentNum+direction*step)),setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;if(setter)setter.call(__sroSlider,String(target));else __sroSlider.value=String(target);__sroSlider.dispatchEvent(new Event('input',{bubbles:true,composed:true}));__sroSlider.dispatchEvent(new Event('change',{bubbles:true}));}else{__sroSlider.focus?.();const key=direction>0?'ArrowRight':'ArrowLeft';__sroSlider.dispatchEvent(new KeyboardEvent('keydown',{key,code:key,bubbles:true,cancelable:true,composed:true}));__sroSlider.dispatchEvent(new KeyboardEvent('keyup',{key,code:key,bubbles:true,cancelable:true,composed:true}));}__sroState.sliderMoves++;__sroState.lastAction='set-slider';__sroState.lastActionAt=__sroNow;return __sroWait('Chat 추론 슬라이더 이동 반영 대기',{action:'set-slider',strategy:__sroInputRange?'native-range':'keyboard'});}}
                  if(__sroPerformance){const sr=__sroSlider.getBoundingClientRect(),cy=sr.top+sr.height/2,small=[...__sroPerformance.querySelectorAll('span')].filter(e=>e!==__sroSlider&&__sroVisible(e)).map(e=>({e,r:e.getBoundingClientRect()})).filter(x=>x.r.width>=4&&x.r.width<=12&&x.r.height>=4&&x.r.height<=12&&Math.abs((x.r.top+x.r.height/2)-cy)<=16).sort((a,b)=>a.r.left-b.r.left);const detents=[];for(const x of small){const cx=x.r.left+x.r.width/2;if(!detents.some(d=>Math.abs(d.cx-cx)<3))detents.push({e:x.e,cx,left:x.r.left});}if(detents.length>=2&&__sroState.sliderMoves<10){let targetIndex;if(detents.length===__sroOrder.length)targetIndex=__sroWantedIndex;else{let currentDetent=0,best=1e9;for(let i=0;i<detents.length;i++){const diff=Math.abs(detents[i].left-sr.left);if(diff<best){best=diff;currentDetent=i;}}targetIndex=currentDetent+(__sroWantedIndex-__sroCurrentIndex);}if(targetIndex>=0&&targetIndex<detents.length){__sroState.sliderMoves++;__sroState.lastAction='set-slider-detent';__sroState.lastActionAt=__sroNow;__sroSave();__sroClick(detents[targetIndex].e);return result('UI_WAIT','Chat 추론 detent 반영 대기',__sroDiagnostics({action:'set-slider-detent',strategy:'detent',detentCount:detents.length,targetIndex}));}}}
                  let track=__sroSlider.parentElement;for(let depth=0;track&&depth<5;depth++){const r=track.getBoundingClientRect();if(r.width>=120&&r.height<=48)break;track=track.parentElement;}if(track&&__sroState.sliderMoves<10){const r=track.getBoundingClientRect(),ratio=__sroWantedIndex/Math.max(1,__sroOrder.length-1),x=r.left+r.width*ratio,y=r.top+r.height/2,hit=document.elementFromPoint?.(x,y)||null,target=hit&&track.contains(hit)?hit:track,init={bubbles:true,cancelable:true,composed:true,clientX:x,clientY:y,button:0};try{if(typeof PointerEvent==='function'){target.dispatchEvent(new PointerEvent('pointerdown',{...init,buttons:1,pointerId:1,pointerType:'mouse',isPrimary:true}));target.dispatchEvent(new PointerEvent('pointerup',{...init,buttons:0,pointerId:1,pointerType:'mouse',isPrimary:true}));}}catch(_){}target.dispatchEvent(new MouseEvent('mousedown',{...init,buttons:1}));target.dispatchEvent(new MouseEvent('mouseup',{...init,buttons:0}));target.dispatchEvent(new MouseEvent('click',{...init,buttons:0}));__sroState.sliderMoves++;__sroState.lastAction='set-slider-track';__sroState.lastActionAt=__sroNow;return __sroWait('Chat 추론 track 반영 대기',{action:'set-slider-track',strategy:'geometry',hitTarget:__sroLabel(target)});}
                }
                if(__sroOpen.length===0&&__sroRoot&&__sroMay(__sroState.rootClicks,2)){__sroState.rootClicks++;__sroState.lastAction='open-reasoning-popover';__sroState.lastActionAt=__sroNow;__sroSave();__sroClick(__sroRoot);return result('UI_WAIT','Chat 추론 선택기 열림 대기',__sroDiagnostics({action:'open-reasoning-popover'}));}
                if(__sroElapsed>=__sroTimeoutMs||__sroState.attempts>=32)return result(__sroRoot?'CHAT_REASONING_SLIDER_NOT_FOUND':'CHAT_REASONING_TRIGGER_NOT_FOUND','현재 Chat 추론 UI를 제한시간 안에 준비하지 못했습니다.',__sroDiagnostics({action:'selector-timeout'}));
                return __sroWait('현재 Chat 추론 제어 탐색 대기',{action:__sroOpen.length>0?'wait-slider':'wait-trigger'});
                """
                .replace("__WANTED__", SelfRunScript.quote(wanted))
                .replace("__ORDINAL__", String.valueOf(ordinal))
                .replace("__RUN_ID__", SelfRunScript.quote(runId))
                .replace("__CAPTURE_ONLY__", String.valueOf(captureOnly));
    }
}
