package com.shaterguy.chatgptselfrun;

/** Chat bootstrap adapter for the one-tap model menu and horizontal reasoning slider. */
final class ChatReasoningDom {
    private ChatReasoningDom() {}

    static String inline(String selection, String runId) {
        String wanted = ChatReasoningPreferenceStore.normalize(selection);
        int ordinal = ChatReasoningPreferenceStore.ordinal(wanted);
        if (ordinal < 0) return "";
        String stateKey = "selfrun-drive:chat-reasoning:" + runId;
        return "const __srcWanted=" + q(wanted) + ",__srcWantedOrdinal=" + ordinal
                + ",__srcStateKey=" + q(stateKey) + ";"
                + "const __srcLevel=s=>{const v=exactText(s);if(v.includes('extra high')||v.includes('very high')||v.includes('xhigh')||v.includes('maximum')||v.includes('매우 높음')||v.includes('최대'))return'xhigh';if(v==='pro'||v.startsWith('pro ')||v.endsWith(' pro')||v.includes('프로'))return'pro';if(v.includes('medium')||v.includes('중간')||v.includes('표준'))return'medium';if(v.includes('high')||v.includes('extended')||v.includes('높음')||v.includes('확장'))return'high';if(v.includes('instant')||v.includes('flash')||v.includes('빠른')||v.includes('즉시'))return'instant';return''};"
                + "const __srcPopupSelector='[role=\"menu\"],[role=\"listbox\"],[role=\"dialog\"],[data-radix-popper-content-wrapper],[data-slot*=\"popover\"],[data-slot*=\"menu\"]';"
                + "const __srcForbidden=e=>/(send|submit|보내기|stop|중지|microphone|마이크|voice|음성|attach|첨부|upload|업로드|new chat|new conversation|새 채팅|새 대화)/.test(labelOf(e)+' '+exactText(e?.dataset?.testid||''));"
                + "const __srcTriggerScore=e=>{const label=labelOf(e),testid=exactText(e?.dataset?.testid||''),popup=e.getAttribute('aria-haspopup')||'',expanded=e.hasAttribute('aria-expanded');let score=0;if(__srcLevel(label))score+=120;if(/reason|thinking|추론/.test(label+' '+testid))score+=70;if(/model|모델|gpt|flash/.test(label+' '+testid))score+=45;if(popup&&popup!=='false')score+=35;if(expanded)score+=30;if(e.hasAttribute('aria-controls')||e.hasAttribute('aria-owns'))score+=25;if(e.closest('header'))score+=10;return score};"
                + "const __srcTriggerEntries=[...document.querySelectorAll('button,[role=\"button\"],[role=\"combobox\"],[aria-haspopup],[aria-expanded],[data-testid*=\"model\"],[data-testid*=\"reason\"]')].filter(visible).filter(e=>!e.closest(__srcPopupSelector)).filter(e=>!__srcForbidden(e)).map((element,index)=>({element,index,score:__srcTriggerScore(element)})).filter(entry=>entry.score>0).sort((a,b)=>b.score-a.score||a.index-b.index);const __srcTriggerEntry=__srcTriggerEntries.length?__srcTriggerEntries[0]:null;const __srcTrigger=__srcTriggerEntry?__srcTriggerEntry.element:null;const __srcTriggerScoreValue=__srcTriggerEntry?__srcTriggerEntry.score:0;const __srcTriggerLevel=__srcTrigger?__srcLevel(labelOf(__srcTrigger)):'';"
                + "const __srcControlledIds=__srcTrigger?String(__srcTrigger.getAttribute('aria-controls')||__srcTrigger.getAttribute('aria-owns')||'').split(/\\s+/).filter(Boolean):[];const __srcControlled=__srcControlledIds.map(id=>document.getElementById(id)).find(visible)||null;"
                + "const __srcRawSliders=[...document.querySelectorAll('[role=\"slider\"],input[type=\"range\"]')].filter(visible).filter(e=>e.getAttribute('aria-orientation')!=='vertical');const __srcOpenPopups=[...document.querySelectorAll(__srcPopupSelector)].filter(visible);const __srcPopup=__srcControlled||__srcOpenPopups.find(p=>__srcRawSliders.some(s=>p.contains(s)))||null;"
                + "const __srcSliderScore=e=>{let score=0;if(__srcControlled&&__srcControlled.contains(e))score+=140;if(__srcPopup&&__srcPopup.contains(e))score+=100;if(e.closest(__srcPopupSelector))score+=60;if(__srcLevel(e.getAttribute('aria-valuetext')||''))score+=35;if(e.matches('input[type=\"range\"]'))score+=20;return score};const __srcSliderEntries=__srcRawSliders.map((element,index)=>({element,index,score:__srcSliderScore(element)})).sort((a,b)=>b.score-a.score||a.index-b.index);const __srcSlider=__srcSliderEntries.length?__srcSliderEntries[0].element:null;"
                + "const __srcExpanded=!!__srcTrigger&&(__srcTrigger.getAttribute('aria-expanded')==='true'||!!__srcControlled||!!__srcPopup);"
                + "let __srcState={menuClicks:0,findAttempts:0,setAttempts:0,closeClicks:0,applied:false,at:0};try{const saved=sessionStorage.getItem(__srcStateKey);if(saved)__srcState={...__srcState,...JSON.parse(saved)};}catch(_){}const __srcSave=()=>{try{sessionStorage.setItem(__srcStateKey,JSON.stringify(__srcState));}catch(_){}};const __srcDiagnostics=extra=>({requested:__srcWanted,requestedOrdinal:__srcWantedOrdinal,sliderFound:!!__srcSlider,sliderCandidates:__srcRawSliders.length,triggerFound:!!__srcTrigger,triggerCandidates:__srcTriggerEntries.length,triggerScore:__srcTriggerScoreValue,triggerLabel:__srcTrigger?labelOf(__srcTrigger):'',triggerLevel:__srcTriggerLevel,triggerExpanded:__srcExpanded,controlledPopup:!!__srcControlled,popupFound:!!__srcPopup,menuClicks:__srcState.menuClicks,findAttempts:__srcState.findAttempts,setAttempts:__srcState.setAttempts,closeClicks:__srcState.closeClicks,applied:!!__srcState.applied,...extra});"
                + "if(!__srcSlider){__srcState.findAttempts++;__srcState.at=Date.now();__srcSave();if(__srcState.applied&&(__srcTriggerLevel===__srcWanted||__srcState.closeClicks>0)){try{sessionStorage.removeItem(__srcStateKey);}catch(_){}return result('READY','Chat 추론 슬라이더 적용 확인',__srcDiagnostics({menuClosed:true}));}if(__srcTrigger&&!__srcExpanded&&__srcState.menuClicks<1){__srcState.menuClicks++;__srcState.at=Date.now();__srcSave();__srcTrigger.focus?.();__srcTrigger.click();return result('UI_WAIT','Chat 모델 메뉴 1회 열기 반영 대기',__srcDiagnostics({action:'open-menu'}));}return result('UI_WAIT',__srcTrigger?'Chat 추론 슬라이더 대기':'Chat 추론 선택기 탐색 대기',__srcDiagnostics({action:__srcTrigger?'wait-slider':'wait-trigger',exhausted:__srcState.findAttempts>=8}));}"
                + "const __srcInput=typeof HTMLInputElement!=='undefined'&&__srcSlider instanceof HTMLInputElement&&__srcSlider.type==='range';const __srcNum=(value,fallback)=>{if(value==null||String(value).trim()==='')return fallback;const n=Number(value);return Number.isFinite(n)?n:fallback};const __srcMin=__srcNum(__srcSlider.getAttribute('aria-valuemin'),__srcInput?__srcNum(__srcSlider.min,0):0);const __srcMax=__srcNum(__srcSlider.getAttribute('aria-valuemax'),__srcInput?__srcNum(__srcSlider.max,100):100);if(!Number.isFinite(__srcMin)||!Number.isFinite(__srcMax)||__srcMax<=__srcMin)return result('UI_WAIT','Chat 추론 슬라이더 범위 정보 대기',__srcDiagnostics({min:__srcMin,max:__srcMax}));"
                + "const __srcStepDefault=__srcInput?__srcNum(__srcSlider.step,1):(__srcMax-__srcMin)/4;const __srcStep=__srcStepDefault>0?__srcStepDefault:(__srcMax-__srcMin)/4;const __srcRatio=__srcWantedOrdinal/4;const __srcRawTarget=__srcMin+(__srcMax-__srcMin)*__srcRatio;const __srcTarget=Math.max(__srcMin,Math.min(__srcMax,__srcMin+Math.round((__srcRawTarget-__srcMin)/__srcStep)*__srcStep));const __srcCurrent=__srcNum(__srcSlider.getAttribute('aria-valuenow'),__srcInput?__srcNum(__srcSlider.value,NaN):NaN);const __srcTextLevel=__srcLevel(__srcSlider.getAttribute('aria-valuetext')||'');const __srcTolerance=Math.max(0.0001,__srcStep/2);const __srcAtTarget=__srcTextLevel===__srcWanted||(Number.isFinite(__srcCurrent)&&Math.abs(__srcCurrent-__srcTarget)<=__srcTolerance);"
                + "if(__srcAtTarget){__srcState.applied=true;__srcState.at=Date.now();__srcSave();if(__srcState.closeClicks<2){__srcState.closeClicks++;__srcSave();if(__srcTrigger){__srcTrigger.focus?.();__srcTrigger.click();}else{__srcSlider.focus?.();try{__srcSlider.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true,cancelable:true,composed:true}));__srcSlider.dispatchEvent(new KeyboardEvent('keyup',{key:'Escape',code:'Escape',bubbles:true,cancelable:true,composed:true}));}catch(_){}}return result('UI_WAIT','Chat 추론 적용 완료 · 메뉴 닫힘 확인',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,valueText:__srcSlider.getAttribute('aria-valuetext')||'',action:'close-menu'}));}return result('UI_WAIT','Chat 추론 적용 완료 · 메뉴 닫힘 대기',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,valueText:__srcSlider.getAttribute('aria-valuetext')||'',action:'wait-menu-close'}));}"
                + "if(__srcState.setAttempts>=4)return result('UI_WAIT','Chat 추론 슬라이더 적용 확인 실패 · 전송 차단',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,exhausted:true}));let __srcChanged=false;if(__srcInput){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;if(setter)setter.call(__srcSlider,String(__srcTarget));else __srcSlider.value=String(__srcTarget);__srcSlider.dispatchEvent(new Event('input',{bubbles:true,composed:true}));__srcSlider.dispatchEvent(new Event('change',{bubbles:true}));__srcChanged=true;}else{const thumb=__srcSlider.getBoundingClientRect();let node=__srcSlider.parentElement,track=null;for(let depth=0;node&&depth<6;depth++,node=node.parentElement){const r=node.getBoundingClientRect();if(r.width>=120&&r.width>=Math.max(thumb.width*2,120)&&r.height<=96){track=node;break;}}if(track){const r=track.getBoundingClientRect(),ratio=Math.max(0.01,Math.min(0.99,__srcRatio)),x=r.left+r.width*ratio,y=r.top+r.height/2,hit=document.elementFromPoint?.(x,y)||track;const common={bubbles:true,cancelable:true,composed:true,clientX:x,clientY:y,button:0};try{if(typeof PointerEvent==='function'){hit.dispatchEvent(new PointerEvent('pointerdown',{...common,buttons:1,pointerId:1,pointerType:'touch',isPrimary:true}));hit.dispatchEvent(new PointerEvent('pointermove',{...common,buttons:1,pointerId:1,pointerType:'touch',isPrimary:true}));hit.dispatchEvent(new PointerEvent('pointerup',{...common,buttons:0,pointerId:1,pointerType:'touch',isPrimary:true}));}}catch(_){}hit.dispatchEvent(new MouseEvent('mousedown',{...common,buttons:1}));hit.dispatchEvent(new MouseEvent('mousemove',{...common,buttons:1}));hit.dispatchEvent(new MouseEvent('mouseup',{...common,buttons:0}));hit.dispatchEvent(new MouseEvent('click',{...common,buttons:0}));__srcChanged=true;}}__srcState.setAttempts++;__srcState.at=Date.now();__srcSave();return result('UI_WAIT','Chat 추론 슬라이더 이동 반영 대기',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,changed:__srcChanged,action:'set-slider'}));";
    }

    private static String q(String value) { return SelfRunScript.quote(value); }
}
