package com.shaterguy.chatgptselfrun;

/** Chat bootstrap adapter for the one-tap model menu and horizontal reasoning slider. */
final class ChatReasoningDom {
    private ChatReasoningDom() {}

    static String inline(String selection, String runId) {
        String wanted = ChatReasoningPreferenceStore.normalize(selection);
        int ordinal = ChatReasoningPreferenceStore.ordinal(wanted);
        if (ordinal < 0) return "";
        String stateKey = "selfrun-drive:chat-reasoning:" + runId;
        return "const __srcWanted=" + q(wanted) + ",__srcWantedOrdinal=" + ordinal
                + ",__srcStateKey=" + q(stateKey) + ";"
                + "const __srcLevel=s=>{const v=exactText(s);if(v.includes('extra high')||v.includes('very high')||v.includes('xhigh')||v.includes('매우 높음')||v.includes('최대'))return'xhigh';if(v==='pro'||v.startsWith('pro ')||v.endsWith(' pro')||v.includes('프로'))return'pro';if(v.includes('medium')||v.includes('중간')||v.includes('표준'))return'medium';if(v.includes('high')||v.includes('높음')||v.includes('확장'))return'high';if(v.includes('instant')||v.includes('빠른')||v.includes('즉시'))return'instant';return''};"
                + "const __srcComposerRect=composer.getBoundingClientRect();const __srcNear=e=>{if(!e)return false;const r=e.getBoundingClientRect();return r.bottom>=__srcComposerRect.top-280&&r.top<=__srcComposerRect.bottom+220&&r.right>=__srcComposerRect.left-240&&r.left<=__srcComposerRect.right+240};"
                + "const __srcSliders=[...document.querySelectorAll('[role=\"slider\"],input[type=\"range\"]')].filter(visible).filter(e=>__srcNear(e)&&e.getAttribute('aria-orientation')!=='vertical');const __srcSlider=__srcSliders[0]||null;"
                + "const __srcTriggers=[...document.querySelectorAll('button,[role=\"button\"],[aria-haspopup],[aria-expanded],[data-testid*=\"model\"]')].filter(visible).filter(__srcNear).filter(e=>!e.closest('[role=\"menu\"],[role=\"listbox\"],[role=\"dialog\"]')).filter(e=>!/(send|보내기|microphone|마이크|voice|음성)/.test(labelOf(e)));const __srcTrigger=__srcTriggers.find(e=>!!__srcLevel(labelOf(e)))||__srcTriggers.find(e=>/model|모델/.test(labelOf(e)+' '+exactText(e.dataset?.testid||'')))||null;const __srcTriggerLevel=__srcTrigger?__srcLevel(labelOf(__srcTrigger)):'';const __srcExpanded=!!__srcTrigger&&__srcTrigger.getAttribute('aria-expanded')==='true';"
                + "let __srcState={menuClicks:0,setAttempts:0,closeClicks:0,applied:false,at:0};try{const saved=sessionStorage.getItem(__srcStateKey);if(saved)__srcState={...__srcState,...JSON.parse(saved)};}catch(_){}const __srcSave=()=>{try{sessionStorage.setItem(__srcStateKey,JSON.stringify(__srcState));}catch(_){}};const __srcDiagnostics=extra=>({requested:__srcWanted,requestedOrdinal:__srcWantedOrdinal,sliderFound:!!__srcSlider,triggerFound:!!__srcTrigger,triggerLevel:__srcTriggerLevel,triggerExpanded:__srcExpanded,menuClicks:__srcState.menuClicks,setAttempts:__srcState.setAttempts,closeClicks:__srcState.closeClicks,applied:!!__srcState.applied,...extra});"
                + "if(!__srcSlider){if(__srcState.applied&&(__srcTriggerLevel===__srcWanted||__srcState.closeClicks>0)){try{sessionStorage.removeItem(__srcStateKey);}catch(_){}return result('READY','Chat 추론 슬라이더 적용 확인',__srcDiagnostics({menuClosed:true}));}if(__srcTrigger&&!__srcExpanded&&__srcState.menuClicks<1){__srcState.menuClicks++;__srcState.at=Date.now();__srcSave();__srcTrigger.focus?.();__srcTrigger.click();return result('UI_WAIT','Chat 모델 메뉴 1회 열기 반영 대기',__srcDiagnostics({action:'open-menu'}));}return result('UI_WAIT','Chat 추론 슬라이더 대기',__srcDiagnostics({action:'wait-slider'}));}"
                + "const __srcInput=typeof HTMLInputElement!=='undefined'&&__srcSlider instanceof HTMLInputElement&&__srcSlider.type==='range';const __srcNum=(value,fallback)=>{const n=Number(value);return Number.isFinite(n)?n:fallback};const __srcMin=__srcNum(__srcSlider.getAttribute('aria-valuemin'),__srcInput?__srcNum(__srcSlider.min,0):NaN);const __srcMax=__srcNum(__srcSlider.getAttribute('aria-valuemax'),__srcInput?__srcNum(__srcSlider.max,100):NaN);if(!Number.isFinite(__srcMin)||!Number.isFinite(__srcMax)||__srcMax<=__srcMin)return result('UI_WAIT','Chat 추론 슬라이더 범위 정보 대기',__srcDiagnostics({min:__srcMin,max:__srcMax}));"
                + "const __srcStepDefault=__srcInput?__srcNum(__srcSlider.step,1):(__srcMax-__srcMin)/4;const __srcStep=__srcStepDefault>0?__srcStepDefault:(__srcMax-__srcMin)/4;const __srcRatio=__srcWantedOrdinal/4;const __srcRawTarget=__srcMin+(__srcMax-__srcMin)*__srcRatio;const __srcTarget=Math.max(__srcMin,Math.min(__srcMax,__srcMin+Math.round((__srcRawTarget-__srcMin)/__srcStep)*__srcStep));const __srcCurrent=__srcNum(__srcSlider.getAttribute('aria-valuenow'),__srcInput?__srcNum(__srcSlider.value,NaN):NaN);const __srcTextLevel=__srcLevel(__srcSlider.getAttribute('aria-valuetext')||'');const __srcTolerance=Math.max(0.0001,__srcStep/2);const __srcAtTarget=__srcTextLevel===__srcWanted||(Number.isFinite(__srcCurrent)&&Math.abs(__srcCurrent-__srcTarget)<=__srcTolerance);"
                + "if(__srcAtTarget){__srcState.applied=true;__srcState.at=Date.now();__srcSave();if(__srcState.closeClicks<2){__srcState.closeClicks++;__srcSave();if(__srcTrigger){__srcTrigger.focus?.();__srcTrigger.click();}else{__srcSlider.focus?.();try{__srcSlider.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true,cancelable:true,composed:true}));__srcSlider.dispatchEvent(new KeyboardEvent('keyup',{key:'Escape',code:'Escape',bubbles:true,cancelable:true,composed:true}));}catch(_){}}return result('UI_WAIT','Chat 추론 적용 완료 · 메뉴 닫힘 확인',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,valueText:__srcSlider.getAttribute('aria-valuetext')||'',action:'close-menu'}));}return result('UI_WAIT','Chat 추론 적용 완료 · 메뉴 닫힘 대기',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,valueText:__srcSlider.getAttribute('aria-valuetext')||'',action:'wait-menu-close'}));}"
                + "if(__srcState.setAttempts>=4)return result('UI_WAIT','Chat 추론 슬라이더 적용 확인 실패 · 전송 차단',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,exhausted:true}));let __srcChanged=false;if(__srcInput){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;if(setter)setter.call(__srcSlider,String(__srcTarget));else __srcSlider.value=String(__srcTarget);__srcSlider.dispatchEvent(new Event('input',{bubbles:true,composed:true}));__srcSlider.dispatchEvent(new Event('change',{bubbles:true,composed:true}));__srcChanged=true;}else{const thumb=__srcSlider.getBoundingClientRect();let node=__srcSlider.parentElement,track=null;for(let depth=0;node&&depth<6;depth++,node=node.parentElement){const r=node.getBoundingClientRect();if(r.width>=120&&r.width>=Math.max(thumb.width*2,120)&&r.height<=96){track=node;break;}}if(track){const r=track.getBoundingClientRect(),ratio=Math.max(0.01,Math.min(0.99,__srcRatio)),x=r.left+r.width*ratio,y=r.top+r.height/2,hit=document.elementFromPoint?.(x,y)||track;const common={bubbles:true,cancelable:true,composed:true,clientX:x,clientY:y,button:0};try{if(typeof PointerEvent==='function'){hit.dispatchEvent(new PointerEvent('pointerdown',{...common,buttons:1,pointerId:1,pointerType:'touch',isPrimary:true}));hit.dispatchEvent(new PointerEvent('pointermove',{...common,buttons:1,pointerId:1,pointerType:'touch',isPrimary:true}));hit.dispatchEvent(new PointerEvent('pointerup',{...common,buttons:0,pointerId:1,pointerType:'touch',isPrimary:true}));}}catch(_){}hit.dispatchEvent(new MouseEvent('mousedown',{...common,buttons:1}));hit.dispatchEvent(new MouseEvent('mousemove',{...common,buttons:1}));hit.dispatchEvent(new MouseEvent('mouseup',{...common,buttons:0}));hit.dispatchEvent(new MouseEvent('click',{...common,buttons:0}));__srcChanged=true;}}__srcState.setAttempts++;__srcState.at=Date.now();__srcSave();return result('UI_WAIT','Chat 추론 슬라이더 이동 반영 대기',__srcDiagnostics({current:__srcCurrent,target:__srcTarget,changed:__srcChanged,action:'set-slider'}));";
    }

    private static String q(String value) { return SelfRunScript.quote(value); }
}
