package com.shaterguy.chatgptselfrun;

/** Passive, privacy-safe composer diagnostics used only after VirtualDisplay reattachment. */
final class SelfRunContinuationDiagnosticsDom {
    private SelfRunContinuationDiagnosticsDom() {}

    static String snapshot() {
        return """
                (()=>{try{
                const now=performance.now();
                const selector='textarea,[contenteditable],[role="textbox"],.ProseMirror,[data-lexical-editor="true"],#prompt-textarea,[data-testid="prompt-textarea"]';
                const scrub=s=>String(s??'').replace(/\\s+/g,' ').trim().replace(/prompt/gi,'p~').replace(/token/gi,'t~').replace(/cookie/gi,'c~').replace(/authorization/gi,'a~').replace(/password/gi,'pw~').replace(/chatgpt\\.com/gi,'cg~').replace(/drive\\.google\\.com/gi,'dg~').replace(/docs\\.google\\.com/gi,'docs~').replace(/oauth/gi,'o~').replace(/bearer/gi,'b~').replace(/[^A-Za-z0-9_.:~#-]/g,'').slice(0,24);
                const ce=e=>String(e?.getAttribute?.('contenteditable')||'').trim().toLowerCase();
                const editable=e=>!!e&&(!!e.isContentEditable||(e.hasAttribute?.('contenteditable')&&ce(e)!=='false'));
                const semantic=e=>!!e&&e.nodeType===1&&(e.matches?.('textarea,[role="textbox"],.ProseMirror,[data-lexical-editor="true"]')||editable(e)||e.id==='prompt-textarea'||e.dataset?.testid==='prompt-textarea');
                const cls=e=>{const v=typeof e?.className==='string'?e.className:'';return scrub(v.split(/\\s+/).filter(Boolean).slice(0,2).join('.'));};
                const sig=e=>{if(!e||e.nodeType!==1)return'none';const a=[];const id=scrub(e.id),r=scrub(e.getAttribute?.('role')),c=scrub(ce(e)),d=scrub(e.dataset?.testid),k=cls(e);if(id)a.push('i='+id);if(r)a.push('r='+r);if(c)a.push('ceattr='+c);a.push('semantic='+(semantic(e)?1:0));if(d)a.push('d='+d);if(k)a.push('c='+k);return String(e.tagName||'').toLowerCase()+(a.length?','+a.join(','):'');};
                const mini=e=>{if(!e||e.nodeType!==1)return'none';let x=String(e.tagName||'').toLowerCase();const r=e.getAttribute?.('role'),c=ce(e),k=cls(e);if(r==='textbox')x+=':r=t';if(c==='plaintext-only')x+=':ce=p';else if(c==='true')x+=':ce=t';else if(c==='false')x+=':ce=f';if(k)x+=':c='+k.slice(0,14);return x;};
                const count=(root,s)=>{try{return root?.querySelectorAll?.(s)?.length||0;}catch(_){return 0;}};
                const census=root=>({ta:count(root,'textarea'),inp:count(root,'input'),ca:count(root,'[contenteditable]'),ct:count(root,'[contenteditable="true"]'),cp:count(root,'[contenteditable="plaintext-only"]'),cf:count(root,'[contenteditable="false"]'),tb:count(root,'[role="textbox"]'),pm:count(root,'.ProseMirror'),lx:count(root,'[data-lexical-editor="true"]'),fm:count(root,'form'),mn:count(root,'main'),ifr:count(root,'iframe')});
                const semCount=root=>count(root,selector);
                const semIn=n=>{if(!n||n.nodeType!==1)return false;if(semantic(n))return true;try{return !!n.querySelector?.(selector);}catch(_){return false;}};
                let st=window.__selfRunDeepContinuationDiag;
                if(!st||st.done||now-Number(st.created||0)>5000){try{st?.obs?.disconnect?.();}catch(_){}st={created:now,stage:0,mut:0,add:0,rem:0,attr:0,sa:0,sr:0,raf:0,done:false,best:null,bestPt:'-',via:'-',iframeBest:null,shadowBest:null};try{st.obs=new MutationObserver(ms=>{for(const m of ms){st.mut++;if(m.type==='childList'){st.add+=m.addedNodes?.length||0;st.rem+=m.removedNodes?.length||0;for(const n of m.addedNodes||[])if(semIn(n))st.sa++;for(const n of m.removedNodes||[])if(semIn(n))st.sr++;}else if(m.type==='attributes')st.attr++;}});st.obs.observe(document.documentElement||document,{subtree:true,childList:true,attributes:true,attributeFilter:['contenteditable','role','id','data-testid','class']});}catch(_){}try{const tick=()=>{if(st.done||performance.now()-st.created>2500)return;st.raf++;requestAnimationFrame(tick);};requestAnimationFrame(tick);}catch(_){}window.__selfRunDeepContinuationDiag=st;}
                const stage=st.stage++;
                if(stage===0){const c=census(document);const p=location.pathname.split('/').filter(Boolean);const route=p[0]==='c'?'c':(p.includes('g')?'g':'o');const sh=[...document.querySelectorAll('*')].filter(e=>{try{return !!e.shadowRoot;}catch(_){return false;}}).length;return ['v=4','s=0','r='+route,'seg='+p.length,'rd='+document.readyState,'vis='+(document.visibilityState||'na'),'f='+(document.hasFocus?.()?1:0),'w='+(innerWidth||0),'h='+(innerHeight||0),'ta='+c.ta,'in='+c.inp,'ca='+c.ca,'ct='+c.ct,'cp='+c.cp,'cf='+c.cf,'tb='+c.tb,'pm='+c.pm,'lx='+c.lx,'fm='+c.fm,'mn='+c.mn,'if='+c.ifr,'sh='+sh,'ae='+sig(document.activeElement)].join(';');}
                const score=e=>{if(!e||e.nodeType!==1)return-1;let s=0;if(e.matches?.('textarea'))s+=120;if(editable(e))s+=110;if(e.getAttribute?.('role')==='textbox')s+=100;if(e.id==='prompt-textarea'||e.dataset?.testid==='prompt-textarea')s+=95;if(e.matches?.('.ProseMirror,[data-lexical-editor="true"]'))s+=90;if(e.matches?.('input:not([type="hidden"]):not([type="button"]):not([type="submit"])'))s+=70;if(e.closest?.('form'))s+=10;return s;};
                const sample=()=>{const xs=[.10,.25,.50,.75,.90],ys=[.65,.75,.85,.92,.97];let best=null,bestScore=-1,bestPt='-',via='-';let fallback=null,stack='-';for(const yf of ys){for(const xf of xs){const x=Math.max(0,Math.min(innerWidth-1,Math.round(innerWidth*xf))),y=Math.max(0,Math.min(innerHeight-1,Math.round(innerHeight*yf)));let es=[];try{es=document.elementsFromPoint(x,y)||[];}catch(_){}if(xf===.50&&yf===.92){fallback=es[0]||fallback;stack=es.slice(0,3).map(mini).join('>')||'-';}for(const e of es.slice(0,8)){let q=score(e);if(q>bestScore){best=e;bestScore=q;bestPt=Math.round(xf*100)+','+Math.round(yf*100);via='self';}let a=e;for(let d=0;d<6&&a;d++,a=a.parentElement){q=score(a);if(q>bestScore){best=a;bestScore=q;bestPt=Math.round(xf*100)+','+Math.round(yf*100);via='anc';}}try{const child=e.querySelector?.(selector);q=score(child);if(child&&q>bestScore){best=child;bestScore=q;bestPt=Math.round(xf*100)+','+Math.round(yf*100);via='desc';}}catch(_){}}}}if(!best||bestScore<=0){best=fallback;bestPt='50,92';via='fallback';}return{best,bestPt,via,stack};};
                const shadowScan=root=>{const out={roots:0,sem:0,best:null};const walk=(r,depth)=>{if(!r||depth>5)return;let all=[];try{all=[...r.querySelectorAll('*')];}catch(_){}for(const e of all){let sr=null;try{sr=e.shadowRoot;}catch(_){}if(!sr)continue;out.roots++;const n=semCount(sr);out.sem+=n;if(!out.best&&n){try{out.best=sr.querySelector(selector);}catch(_){}}walk(sr,depth+1);}};walk(root,0);return out;};
                const iframeScan=()=>{const out={total:0,same:0,sem:0,best:null};let fs=[];try{fs=[...document.querySelectorAll('iframe')];}catch(_){}out.total=fs.length;for(const f of fs.slice(0,16)){let d=null;try{d=f.contentDocument;}catch(_){}if(!d)continue;out.same++;const n=semCount(d);out.sem+=n;if(!out.best&&n){try{out.best=d.querySelector(selector);}catch(_){}}}return out;};
                if(stage===1){const q=sample(),fr=iframeScan(),sh=shadowScan(document);st.best=q.best;st.bestPt=q.bestPt;st.via=q.via;st.iframeBest=fr.best;st.shadowBest=sh.best;return ['v=4','s=1','if='+fr.total,'ifs='+fr.same,'ifsem='+fr.sem,'sh='+sh.roots,'shsem='+sh.sem,'via='+q.via,'pt='+q.bestPt,'best='+sig(q.best),'stk='+q.stack].join(';');}
                const anc=[];let a=st.best;for(let d=0;d<5&&a;d++,a=a.parentElement)anc.push(mini(a));const age=Math.max(0,Math.round(performance.now()-st.created));const out=['v=4','s=2','age='+age,'mut='+st.mut,'add='+st.add,'rem='+st.rem,'at='+st.attr,'sa='+st.sa,'sr='+st.sr,'raf='+st.raf,'pt='+st.bestPt,'via='+st.via,'anc='+anc.join('>'),'ib='+mini(st.iframeBest),'sb='+mini(st.shadowBest)].join(';');st.done=true;try{st.obs?.disconnect?.();}catch(_){}return out;
                }catch(_){return'v=4;s=e';}})()
                """;
    }
}
