package com.shaterguy.chatgptselfrun;
import org.junit.Test;import java.nio.file.*;import static org.junit.Assert.*;
public class SelfRunDriveDev3PolicyTest {
 @Test public void modifiedTimeIsOnlyReadOptimization() throws Exception {String s=src("SelfRunService.java"),p=between(s,"private void pollDriveNow","private void replayTerminalSideEffect");assertTrue(p.contains("DriveSignalParser.scan"));assertTrue(p.contains("scan.unseen"));assertTrue(p.contains("cursorRebased"));assertFalse(p.contains("FUTURE_TURN"));}
 @Test public void commandReceivedIsRequiredBeforeLaterProgressWhenAckIsPending() throws Exception {String st=src("SelfRunStore.java"),a=between(st,"void applyDriveSignals","void repairGuard");assertTrue(a.contains("COMMAND_RECEIVED_REQUIRED"));assertTrue(a.contains("if(x.type==DriveSignalParser.Type.COMMAND_RECEIVED)"));assertTrue(a.contains("clearCommandWait"));}
 @Test public void commandRetryIsUnlimitedButStableMarkerPreventsDuplicateClick() throws Exception {String s=src("SelfRunService.java"),st=src("SelfRunStore.java"),dom=src("SelfRunDom.java");assertTrue(s.contains("SUBMISSION_RETRY_MS = 5 * 60_000L"));assertTrue(st.contains("Integer.MAX_VALUE"));assertTrue(st.contains("pendingDriveSignalCursor"));assertTrue(dom.contains("SUBMISSION_PENDING"));assertTrue(dom.contains("state==='clicked'"));}
 @Test public void resumeDecisionUsesDurableAnchorAndPostAnchorLatestSignal() throws Exception {String st=src("SelfRunStore.java"),b=between(st,"void baselineManualResume","void captureConversationUrl");assertTrue(b.contains("pauseAnchorCursor"));assertTrue(b.contains("DriveResumePolicy.decide"));assertTrue(b.contains("latest"));assertTrue(b.contains("RESTORE_PHASE"));assertTrue(b.contains("POST_ANCHOR"));}
 @Test public void invalidGuardNeverForcesContinuationWithoutCompletionEvidence() throws Exception {String st=src("SelfRunStore.java"),g=between(st,"void repairGuard","void beginManualResumeOverride");assertTrue(g.contains("PHASE_WAIT_DRIVE_COMMIT"));assertTrue(g.contains("int cursor=driveSignalCursor()"));assertTrue(g.contains("cursor-1"));assertTrue(g.contains("Integer.MAX_VALUE"));assertTrue(g.contains("driveRebaselineAuthorized"));assertTrue(g.contains("lastSeenDriveVersion"));assertTrue(g.contains("lastSeenModifiedTime"));assertFalse(g.contains("continuation 강제 진행"));}
 @Test public void validCompletionEvidenceStillRebuildsGuard() throws Exception {String st=src("SelfRunStore.java"),g=between(st,"void repairGuard","void beginManualResumeOverride");assertTrue(g.contains("DriveSignalParser.Type.TURN_COMPLETED"));assertTrue(g.contains("PHASE_DRIVE_COMMIT_GUARD"));assertTrue(g.contains("guardDueAt"));}
 static String src(String f)throws Exception{Path p=Paths.get("app/src/main/java/com/shaterguy/chatgptselfrun/"+f);if(!Files.exists(p))p=Paths.get("src/main/java/com/shaterguy/chatgptselfrun/"+f);return new String(Files.readAllBytes(p), java.nio.charset.StandardCharsets.UTF_8);}static String between(String s,String a,String b){return s.substring(s.indexOf(a),s.indexOf(b));}
}
