package com.shaterguy.chatgptselfrun;
import org.junit.Test;import java.nio.file.*;import static org.junit.Assert.*;
public class SelfRunDriveDev3PolicyTest {
 // Guard recovery regression coverage for Drive completion evidence.
 @Test public void modifiedTimeIsOnlyReadOptimization() throws Exception {String s=src("SelfRunService.java"),p=between(s,"private void pollDriveNow","private void replayTerminalSideEffect");assertTrue(p.contains("DriveSignalParser.scan"));assertTrue(p.contains("scan.unseen"));assertTrue(p.contains("cursorRebased"));assertFalse(p.contains("FUTURE_TURN"));assertFalse(p.contains("MALFORMED"));}
 @Test public void laterProgressImplicitlyAcksMissedCommandReceived() throws Exception {String st=src("SelfRunStore.java"),a=between(st,"void applyDriveSignals","void repairGuard");assertTrue(a.contains("if(awaiting)"));assertTrue(a.contains("clearCommandWait"));assertTrue(a.contains("case TURN_COMPLETED"));}
 @Test public void commandRetryIsUnlimitedAndNeverTerminal() throws Exception {String s=src("SelfRunService.java"),st=src("SelfRunStore.java"),r=between(st,"void prepareCommandRetry","void applyDriveSignals");assertTrue(s.contains("SUBMISSION_RETRY_MS = 5 * 60_000L"));assertFalse(s.contains("maxRetryCount"));assertFalse(s.contains("SUBMISSION_CONFIRMATION_TIMEOUT"));assertTrue(st.contains("Integer.MAX_VALUE"));assertFalse(r.contains("PHASE_PAUSED"));assertFalse(r.contains("PHASE_DONE"));}
 @Test public void resumeDecisionNeverUsesLatestSignalType() throws Exception {String st=src("SelfRunStore.java"),b=between(st,"void baselineManualResume","void captureConversationUrl");assertTrue(b.contains("driveSignalCursor"));assertTrue(b.contains("conversationSyncNextPhase"));assertTrue(b.contains("PHASE_SYNC_CONVERSATION"));assertTrue(b.contains("PHASE_SEND_CONTINUE"));assertFalse(b.contains("event.type"));}
 @Test public void invalidGuardNeverForcesContinuationWithoutCompletionEvidence() throws Exception {String st=src("SelfRunStore.java"),g=between(st,"void repairGuard","void beginManualResumeOverride");assertTrue(g.contains("PHASE_WAIT_DRIVE_COMMIT"));assertTrue(g.contains("driveSignalCursor()-1"));assertTrue(g.contains("Integer.MAX_VALUE"));assertTrue(g.contains("lastSeenDriveVersion"));assertTrue(g.contains("lastSeenModifiedTime"));assertFalse(g.contains("PHASE_READ_NEXT_CONTROL"));assertFalse(g.contains("continuation 강제 진행"));}
 @Test public void validCompletionEvidenceStillRebuildsGuard() throws Exception {String st=src("SelfRunStore.java"),g=between(st,"void repairGuard","void beginManualResumeOverride");assertTrue(g.contains("DriveSignalParser.Type.TURN_COMPLETED"));assertTrue(g.contains("PHASE_DRIVE_COMMIT_GUARD"));assertTrue(g.contains("guardDueAt"));}
 static String src(String f)throws Exception{Path p=Paths.get("app/src/main/java/com/shaterguy/chatgptselfrun/"+f);if(!Files.exists(p))p=Paths.get("src/main/java/com/shaterguy/chatgptselfrun/"+f);return new String(Files.readAllBytes(p), java.nio.charset.StandardCharsets.UTF_8);}static String between(String s,String a,String b){return s.substring(s.indexOf(a),s.indexOf(b));}
}
